[package]
name = "fetcher2_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fetcher2 = { path = "../fetcher2" }
config = { path = "../config"}